In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3,4])

array1

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(4,17,3)

array([ 4,  7, 10, 13, 16])

In [8]:
type(array1)

numpy.ndarray

In [10]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array1.size

4

In [12]:
array2.size

12

In [13]:
array2.shape

(3, 4)

In [14]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [16]:
import numpy as np

bitcoin_array = np.array([970, 1180, 1072, 1348, 2286, 2481,
                          2875, 4703, 4339, 6468, 10234, 14156])

# 여기에 코드를 작성하세요.
bitcoin_array[6:9]

array([2875, 4703, 4339])

In [17]:
import numpy as np

bitcoin_array = np.array([[970, 1180, 1072, 1348, 2286, 2481,
						   2875, 4703, 4339, 6468, 10234, 14156],
						  [514, 428, 1087, 976, 3426, 4448,
						   3262, 6355, 5570, 5801, 14074, 41034]])

# 여기에 코드를 작성하세요.
bitcoin_array[1,6]

np.int64(3262)

In [20]:
import numpy as np

numbers_array = np.arange(1, 101)

# 여기에 코드를 작성하세요.
mask = numbers_array % 2 == 0

numbers_array[mask]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [21]:
import numpy as np

price_array = np.array([30000, 25000, 40000, 60000, 95000, 35000, 50000])
quantity_array = np.array([10, 13, 7, 20, 6, 19, 9])

# 여기에 코드를 작성하세요.
price_array * quantity_array

array([ 300000,  325000,  280000, 1200000,  570000,  665000,  450000])